#!/usr/bin/env node
/* Regenerates app.js's ASSET_SIZES table (the loading bar's byte weights) from the files actually in assets/.
   Run after adding, removing or re-encoding any asset:   node tools/gen_asset_sizes.js
   Every file listed is preloaded behind the landing's loading bar (app.js Assets); a file not on disk is never
   requested, so the table is also the lesson's manifest. */
const fs = require("fs"), path = require("path");
const root = path.resolve(__dirname, ".."), appPath = path.join(root, "app.js");
const SKIP = /(^|\/)(\.DS_Store|Thumbs\.db|desktop\.ini)$/i;
const walk = d => fs.readdirSync(d, { withFileTypes: true }).flatMap(e =>
  e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]);
const rows = walk(path.join(root, "assets"))
  .map(f => path.relative(root, f).split(path.sep).join("/"))
  .filter(f => !SKIP.test(f))
  .sort()
  .map(f => `  ${JSON.stringify(f)}: ${fs.statSync(path.join(root, f)).size}`);
const BEGIN = "/* @asset-sizes:begin (generated by tools/gen_asset_sizes.js - do not edit by hand) */";
const END = "/* @asset-sizes:end */";
const block = `${BEGIN}\nconst ASSET_SIZES = {\n${rows.join(",\n")}\n};\n${END}`;
const src = fs.readFileSync(appPath, "utf8");
const a = src.indexOf("/* @asset-sizes:begin"), b = src.indexOf(END);
if (a < 0 || b < 0) { console.error("app.js has no @asset-sizes markers"); process.exit(1); }
fs.writeFileSync(appPath, src.slice(0, a) + block + src.slice(b + END.length));
console.log(`ASSET_SIZES: ${rows.length} files`);
